fixed NoClassDefFoundError for older android versions (<21). Now use deprecated LeScanRessult (>=18) instead of ScanResult (>=21). changed BLE support detection. now it cheks API version AND  SystemFeatures. fixed some Lint warnings. optimized imports.